sudo: required
services:
  - docker

before_install:
  - docker build -t gaurav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gaurav/react-test npm test

after_success:
  - docker build -t gaurav/multi-client ./client
  - docker build -t gaurav/multi-nginx ./multi
  - docker build -t gaurav/multi-server ./server
  - docker build -t gaurav/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gaurav/multi-client
  - docker push gaurav/multi-nginx
  - docker push gaurav/multi-server
  - docker push gaurav/multi-worker